fix(templates): support spaces in file path in Unity .meta checks

diff --git a/templates/steps/cd.yml b/templates/steps/cd.yml
--- a/templates/steps/cd.yml
+++ b/templates/steps/cd.yml
@@ -9,53 +9,45 @@ steps:
         tarball=$(find . -name "*.tgz")
         tarballFilePaths=$(tar -tf $tarball)
 
-        for filePath in $tarballFilePaths
+        while read -r filePath
         do
           case $filePath in
             *.meta)
               metaFilePath=$filePath
               found=false
               regularFilePath=${metaFilePath%.meta}
-              for otherFilePath in $tarballFilePaths
+              while read -r otherFilePath
               do
                 case $otherFilePath in
                   $regularFilePath/* | $regularFilePath*) # folder or file
-                    if [ $metaFilePath != $otherFilePath ]
+                    if [ "$metaFilePath" != "$otherFilePath" ]
                     then
                       found=true
                       break
                     fi;;
                 esac
-              done
+              done <<< "$tarballFilePaths"
               if [ "$found" = false ]
               then
-                echo "Missing file for Unity meta file '$metaFilePath'." >&2
+                echo "Missing file for Unity meta file '${metaFilePath#"package/"}'." >&2
               fi;;
-          esac
-        done
-
-        for filePath in $tarballFilePaths
-        do
-          case $filePath in
-            *.meta)
-              ;;
             *)
               regularFilePath=$filePath
               found=false
-              for otherFilePath in $tarballFilePaths
+              while read -r otherFilePath
               do
                 case $otherFilePath in
                   $regularFilePath.meta)
                     found=true
                     break;;
                 esac
-              done
+              done <<< "$tarballFilePaths"
               if [ "$found" = false ]
               then
-                echo "Missing Unity meta file for file '$regularFilePath'." >&2
+                echo "Missing Unity meta file for file '${regularFilePath#"package/"}'." >&2
               fi;;
           esac
-        done
+        done <<< "$tarballFilePaths"
 
         rm -f $tarball
       displayName: Check Unity .meta files
