fix(templates): check Unity .meta files after building, not before

diff --git a/templates/steps/ci.yml b/templates/steps/ci.yml
--- a/templates/steps/ci.yml
+++ b/templates/steps/ci.yml
@@ -7,19 +7,6 @@ parameters:
 
 steps:
 - ${{ if parameters.unityProject }}:
-  - bash: |
-      for entry in $(find . -not -path "*/\.*" -not -path . -not -name "*.meta")
-        do if [ ! -f "$entry.meta" ]
-          then echo "Missing Unity meta file for '$entry'." >&2
-        fi
-      done
-      for entry in $(find . -not -path "*/\.*" -not -path . -name "*.meta")
-        do if [ ! -f ${entry::-5} ] && [ ! -d ${entry::-5} ]; then
-          echo "Missing file for Unity meta file '$entry'." >&2
-        fi
-      done
-    displayName: Check Unity .meta files
-    failOnStderr: true
   - powershell: |
       Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
       Install-Module UnitySetup -Scope CurrentUser -Force
@@ -70,3 +57,17 @@ steps:
     msbuildArchitecture: x64
     ${{ if parameters.unityProject }}:
       msbuildArgs: /p:UnityEditorAssembliesPath="$(Unity.Path)Editor/Data/Managed/"
+- ${{ if parameters.unityProject }}:
+  - bash: |
+      for entry in $(find . -not -path "*/\.*" -not -path . -not -name "*.meta")
+        do if [ ! -f "$entry.meta" ]
+          then echo "Missing Unity meta file for '$entry'." >&2
+        fi
+      done
+      for entry in $(find . -not -path "*/\.*" -not -path . -name "*.meta")
+        do if [ ! -f ${entry::-5} ] && [ ! -d ${entry::-5} ]; then
+          echo "Missing file for Unity meta file '$entry'." >&2
+        fi
+      done
+    displayName: Check Unity .meta files
+    failOnStderr: true
