fix(templates): fail on Unity .meta files for no matching file

diff --git a/templates/steps/ci.yml b/templates/steps/ci.yml
--- a/templates/steps/ci.yml
+++ b/templates/steps/ci.yml
@@ -13,7 +13,12 @@ steps:
           then echo "Missing Unity meta file for '$entry'." >&2
         fi
       done
-    displayName: Check if all Unity .meta files exist
+      for entry in $(find . -not -path "*/\.*" -not -path . -name "*.meta")
+        do if [ ! -f ${entry::-5} ] && [ ! -d ${entry::-5} ]; then
+          echo "Missing file for Unity meta file '$entry'." >&2
+        fi
+      done
+    displayName: Check Unity .meta files
     failOnStderr: true
   - powershell: |
       Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
